### ISSUE TITLE
Getting error from file kedro_argo/cli.py line pipeline.node_dependencies as pc.pipeline returns dictionary of pipelines

### ISSUE THREAD

**Issue by rahulsharesth** [nraw/kedro-argo#2]
I am getting error below error when running kedro argo command.

`
  File "/project_environment/lib/python3.7/site-packages/kedro_argo/cli.py", line 31, in argokedro
    dependencies = pipeline.node_dependencies
AttributeError: 'dict' object has no attribute 'node_dependencies'
`

 I can see error is generated from the file _kedro_argo/cli.py_ line _pipeline.node_dependencies_ as in my case _pc.pipeline_ returns dictionary of pipelines. I have multiple pipelines and create_pipelines  return  Dict[str, Pipeline]:

Is there a way to pass pipeline name or handle Dict in kedro_argo?

**Comment by nraw** [comment]
Does the following fit your ask?
#3
